name: Build Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'packages/**'

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        type: string
        default: 'Validate packages'

jobs:
  validate:
    name: Validate packages (${{ github.event.inputs.reason}})
    strategy:
      matrix:
        node-version: [22]
    runs-on: ${{ matrix.node-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --prod --frozen-lockfile

      - name: Validate
        run: pnpm check
